version: '3.9'

services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: documentAssistant
      MYSQL_USER: kelvin
      MYSQL_PASSWORD: documentAssistant
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8021:8080

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8022:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: documentAssistant
      DATABASE_USER: kelvin
      DATABASE_PASSWORD: documentAssistant
      DATABASE_HOST: db
      DATABASE_PORT: 3306

volumes:
  mysql_data:
